apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: moshe-pod  
spec:
 containers: 
 - name: app1 
   image: supergiantkir/animals:bear 
   ports: 
   - containerPort: 80
   volumeMounts:
   - name: app-storage
     mountPath: /storage
 - name: app2
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 8080
   volumeMounts:
   - name: app-storage
     mountPath: /storage
  volumes:
  - name: app-storage
    hostPath:
     path: /tmp/files
   
